### ISSUE TITLE
Research using Polygon for Apocryph DAO

### ISSUE THREAD

**Issue by branimirangelov** [comrade-coop/apocryph-dao-bot#11]

**Comment by bojidar-bg** [comment]
(Note, consider _not_ deploying to mainnet until issues such as https://github.com/comrade-coop/apocryph-dao/issues/2 are resolved (: )

**Comment by aph5nt** [comment]
@branimirangelov @todorkolev @bojidar-bg -- please provide your addresses 
I want to use them while deploying contracts to polygon test net

**Comment by aph5nt** [comment]
```

PS C:\Workplace\apocryph-dao> npx hardhat run --network polygon_mumbai scripts/deploy.js
=> Config file to deploy on 'polygon_mumbai'? [config/apocryph.json]
INFO: Deploying contracts...
INFO: Signer address is                                  0x307c60a4C8648F82C3F3a5243e563052178554c7 (balance:            2.226095300998812093 ETH)
TRACE: Deploying Comrade (Fixed)...
=> Address for Comrade? [(use dummy)] 0xAE8687d444511a595Cc1EAdbFc1dFe58eB639C5f
INFO: Deployed Comrade (Fixed)                        at 0xAE8687d444511a595Cc1EAdbFc1dFe58eB639C5f (gas:       0 =      0.000000000000000000 ETH)
TRACE: Deploying @todorkolev (Fixed)...
=> Address for @todorkolev? [(use dummy)] 0xa9b4503992c2baFc8126de2F06B17D0De4495927
TRACE: Deploying @branimirangelov (Fixed)...                                                                                   00000000000000 ETH)
=> Address for @branimirangelov? [(use dummy)] 0xC498341E8568aCeec2CAD95e326A2f72572FBB05
INFO: Deployed @branimirangelov (Fixed)               at 0xC498341E8568aCeec2CAD95e326A2f72572FBB05 (gas:       0 =      0.000000000000000000 ETH)                                                                                                            00000000000000 ETH)
TRACE: Deploying @bojidar-bg (Fixed)...
=> Address for @bojidar-bg? [(use dummy)] 0x4019cC8D534BC620e022e9C5002770e068F32871
INFO: Deployed @bojidar-bg (Fixed)                    at 0x4019cC8D534BC620e022e9C5002770e068F32871 (gas:       0 =      0.000000000000000000 ETH)00000000000000 ETH)
TRACE: Deploying @kamilwojciechowski (Fixed)...
=> Address for @kamilwojciechowski? [(use dummy)]
=> Address for @kamilwojciechowski? [(use dummy)] 0x47A85C2721590a639fD728B654e15413c8F23997
INFO: Deployed @kamilwojciechowski (Fixed)            at 0x47A85C2721590a639fD728B654e15413c8F23997 (gas:       0 =      0.000000000000000000 ETH)
TRACE: Deploying Bonding Curve Buy Token (FixedERC20)...
=> Address for Bonding Curve Buy Token? [(deploy TestERC20)] 0x4aC0f506beA54cE63D60839C09Bed20bb8c82636
INFO: Deployed Bonding Curve Buy Token (FixedERC20)   at 0x4aC0f506beA54cE63D60839C09Bed20bb8c82636 (gas:       0 =      0.000000000000000000 ETH)
TRACE: Deploying Core Team (DelegatedGroup)...
INFO: Deployed Core Team (DelegatedGroup)             at 0x0197C7806CfA1bbdB5c444b5c7bB32D88EBbe160 (gas:       0 =      0.000000000000000000 ETH)
TRACE: Deploying Core Team (Voting)...
INFO: Deployed Core Team (Voting)                     at 0x2e4e12a05499b4080f476c589c0030f61B0C105c (gas: 2011706 =      0.020117060000000000 ETH)
TRACE: Deploying Apocryph Token (TokenAgeToken)...
INFO: Deployed Apocryph Token (TokenAgeToken)         at 0x8457AdD8352bB475978edb33281Ad4e7D3471c70 (gas:       0 =      0.000000000000000000 ETH)
TRACE: Deploying Apocryph Token (Vesting)...
INFO: Deployed Apocryph Token (Vesting)               at 0x947199a43AD34ee88349931F24b813CB04cC6C0F (gas: 1797415 =      0.017974149998202585 ETH)
TRACE: Deploying Apocryph DAO (Voting)...
INFO: Deployed Apocryph DAO (Voting)                  at 0xF8F7DFDB377753397D36444017D9d402B6CB491E (gas: 3222877 =      0.032228769996777123 ETH)
TRACE: Deploying Apocryph DAO (Allocations)...
INFO: Deployed Apocryph DAO (Allocations)             at 0xB2503Cf56BA33D70241AaA96f8f622B0Db747229 (gas:       0 =      0.000000000000000000 ETH)
TRACE: Deploying Apocryph Bonding Curve (BondingCurve)...
INFO: Deployed Apocryph Bonding Curve (BondingCurve)  at 0x76a3a828F9D4e478eB2C6623CDf3939fD6C50E92 (gas: 2410252 =      0.024102519997589748 ETH)
INFO: Deployed all contracts
TRACE: Initializing Core Team (DelegatedGroup) ...
INFO: Initialized Core Team (DelegatedGroup)                                                        (gas:       0 =      0.000000000000000000 ETH)
TRACE: Initializing Apocryph Token (TokenAgeToken) ...
WARN: Leftover 3500000000000000000 CRYPH on the signer address
INFO: Initialized Apocryph Token (TokenAgeToken)                                                    (gas:  227516 =      0.002275159999772484 ETH)
INFO: Finished deployment!                                                                        (total: 9669766 =      0.096697659992341940 ETH)
=> Deployment file to write? [deployment/apocryph-1640777270698.json] (node:20160) UnhandledPromiseRejectionWarning: Error: transaction failed (transactionHash="0x836d183dff7c76157a3f17e1c87831801e11bd2a67fcd60829e0b80ec9da41dc", transaction={"hash":"0x836d183dff7c76157a3f17e1c87831801e11bd2a67fcd60829e0b80ec9da41dc","type":0,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x307c60a4C8648F82C3F3a5243e563052178554c7","gasPrice":{"type":"BigNumber","hex":"0x02540be3ff"},"gasLimit":{"type":"BigNumber","hex":"0x030d75"},"to":"0x8457AdD8352bB475978edb33281Ad4e7D3471c70","value":{"type":"BigNumber","hex":"0x00"},"nonce":61,"data":"0x4000aea0000000000000000000000000947199a43ad34ee88349931f24b813cb04cc6c0f0000000000000000000000000000000000000000000000001bc16d674ec8000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000080000000000000000000000000f8f7dfdb377753397d36444017d9d402b6cb491e0000000000000000000000000000000000000000000000000000000001d86f9100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001","r":"0xfe119ad26ee41f2a44737d09c3a0171e197275bfa49b8e7c6e7c1f02bfd03ecd","s":"0x4d57d10e32d2348039a5373de177a68ad3c76022aaeba45debd1fbfd15dacab3","v":160038,"creates":null,"chainId":80001}, receipt={"to":"0x8457AdD8352bB475978edb33281Ad4e7D3471c70","from":"0x307c60a4C8648F82C3F3a5243e563052178554c7","contractAddress":null,"transactionIndex":3,"gasUsed":{"type":"BigNumber","hex":"0x030d75"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008002000000000000000000000000000000000000000000000000000000800000000000000000000100000000004000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000200000880000000000000000000200000000000000000000000000000000000000000000000000000000000004000000000000000000001000000000000000000000000000000100040000000000000000000000000000000000000000000000000000000000000000000100000","blockHash":"0xf753376a1dd361a8847dc74938551ff711fc776467936ce65686699a6ec043fb","transactionHash":"0x836d183dff7c76157a3f17e1c87831801e11bd2a67fcd60829e0b80ec9da41dc","logs":[{"transactionIndex":3,"blockNumber":23271973,"transactionHash":"0x836d183dff7c76157a3f17e1c87831801e11bd2a67fcd60829e0b80ec9da41dc","address":"0x0000000000000000000000000000000000001010","topics":["0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63","0x0000000000000000000000000000000000000000000000000000000000001010","0x000000000000000000000000307c60a4c8648f82c3f3a5243e563052178554c7","0x000000000000000000000000be188d6641e8b680743a4815dfa0f6208038960f"],"data":"0x00000000000000000000000000000000000000000000000000071b78afeac8580000000000000000000000000000000000000000000000001d76227c28c5f182000000000000000000000000000000000000000000000322f8039b5b8ad637d20000000000000000000000000000000000000000000000001d6f070378db292a000000000000000000000000000000000000000000000322f80ab6d43ac1002a","logIndex":6,"blockHash":"0xf753376a1dd361a8847dc74938551ff711fc776467936ce65686699a6ec043fb"}],"blockNumber":23271973,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x04c3b8"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x02540be3ff"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.5.1)
    at Logger.makeError (C:\Workplace\apocryph-dao\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (C:\Workplace\apocryph-dao\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at EthersProviderWrapper.<anonymous> (C:\Workplace\apocryph-dao\node_modules\@ethersproject\providers\src.ts\base-provider.ts:1316:24)
    at step (C:\Workplace\apocryph-dao\node_modules\@ethersproject\providers\lib\base-provider.js:48:23)
    at Object.next (C:\Workplace\apocryph-dao\node_modules\@ethersproject\providers\lib\base-provider.js:29:53)
    at fulfilled (C:\Workplace\apocryph-dao\node_modules\@ethersproject\providers\lib\base-provider.js:20:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of 
an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that 
are not handled will terminate the Node.js process with a non-zero exit code.
=> Deployment file to write? [deployment/apocryph-1640777270698.json]






```
https://mumbai.polygonscan.com/tx/0x836d183dff7c76157a3f17e1c87831801e11bd2a67fcd60829e0b80ec9da41dc

@bojidar-bg
