### ISSUE TITLE
Perper throws exception

### ISSUE THREAD

**Issue by aph5nt** [comrade-coop/apocryph-dao-bot#21]
How to reproduce:
branch:  feature/forward_proposal_events

    public class Init
    {
        private readonly IContext _context;
        public Init(IContext context)
        {
            _context = context;
        }
 
        public async Task RunAsync()
        {
             // WHEN 2 CallActionAsync are invoked, Perper throws an exception
             await _context.CallActionAsync(nameof(BlockchainEvents), Array.Empty<object>()).ConfigureAwait(false);
             await _context.CallActionAsync(nameof(UserInteractions), Array.Empty<object>()).ConfigureAwait(false);
            // WHEN only one of  CallActionAsync is commented, then there is no exception
        }
    }

The pepper exception looks following:

        Exception in thread "DefaultDispatcher-worker-6" java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class 
        java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
        at com.obecto.perper.fabric.StreamService.getIndexType(StreamService.kt:92)
        at com.obecto.perper.fabric.StreamService.createCache(StreamService.kt:128)
        at com.obecto.perper.fabric.StreamService.engageStream(StreamService.kt:115)
        at com.obecto.perper.fabric.StreamService.updateStream(StreamService.kt:99)
        at com.obecto.perper.fabric.StreamService$listenCache$2$1.invokeSuspend(StreamService.kt:79)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by bojidar-bg** [comment]
Worked around in https://github.com/obecto/perper/commit/8f0faa59a198c0a4d20ed7a0bd54f6f06d03535d.

**Comment by aph5nt** [comment]
fixed
